// Brain-wiring doc generator — renders the brain's anatomy (REGIONS + PATHWAYS from
// brainMap.ts) to a committable Mermaid diagram + region table. Generated FROM the code
// so the diagram can never drift from the real wiring: regenerate any time the anatomy
// changes. Pure + deterministic, $0. Consumed by trace/wiring tests (GEN_DOCS=1).
import { REGIONS, PATHWAYS, type RegionId } from './brainMap';

/** Mermaid node id — sanitized region id (hyphens aren't valid bare Mermaid ids). */
function nodeId(id: RegionId): string {
  return id.replace(/-/g, '_');
}

const SIDE_CLASS: Record<string, string> = { left: 'analytical', right: 'generative', center: 'core' };

/** Render the brain wiring as a Mermaid `graph` block (regions as nodes, pathways as edges). */
export function renderWiringMermaid(): string {
  const nodes = REGIONS.map((r) => `  ${nodeId(r.id)}["${r.label}"]:::${SIDE_CLASS[r.side]}`).join('\n');
  const edges = PATHWAYS.map(([a, b]) => `  ${nodeId(a)} --> ${nodeId(b)}`).join('\n');
  return [
    'graph TD',
    nodes,
    edges,
    '  classDef generative fill:#2a0f38,stroke:#d24bff,color:#f3f1fb;',
    '  classDef analytical fill:#08302e,stroke:#36e0d4,color:#f3f1fb;',
    '  classDef core fill:#3a2a10,stroke:#ffb14e,color:#f3f1fb;',
  ].join('\n');
}

/** Render the full brain-wiring markdown doc — Mermaid diagram + a region reference table. */
export function renderWiringDoc(): string {
  const rows = REGIONS.map((r) => {
    const side = r.side === 'left' ? 'Analytical (L)' : r.side === 'right' ? 'Generative (R)' : 'Core';
    return `| \`${r.id}\` | ${r.label} | ${side} | \`${r.doc}\` |`;
  }).join('\n');

  return `# 🧠 Brain wiring

> **Generated from code.** This diagram is rendered from \`REGIONS\` + \`PATHWAYS\` in
> [\`lib/hermes/brainMap.ts\`](../lib/hermes/brainMap.ts) — the single source of truth for
> the brain's anatomy — so it can never drift from the real wiring. Regenerate with
> \`GEN_DOCS=1 npx vitest run wiring\`.
>
> The brain metaphor is an [inspired workflow model](../brain/hemispheres.md), not
> biological. Each region is a real knowledge file or module; each nerve is a directed
> signal the pipeline fires along.

## The map

\`\`\`mermaid
${renderWiringMermaid()}
\`\`\`

Left hemisphere is **analytical** (cyan), right is **generative** (magenta), center is
**core** decision/memory (amber) — the same palette the live Brain Scan uses.

## Regions

| id | Region | Hemisphere | Backing file |
|----|--------|-----------|--------------|
${rows}

${PATHWAYS.length} directed pathways connect them. A song is generated by firing the
pipeline (\`lib/hermes/pipeline.ts\`); the nervous system lights each region as its agent
runs. See [\`ARCHITECTURE.md\`](../ARCHITECTURE.md) for the full module map.
`;
}
